### ISSUE TITLE
我按照教程自己编译了几个包，ua2f雀氏启动了，当我打开登录giwifi网址时显示403，用你的包就没问题，为啥啊

### ISSUE THREAD

**Issue by Yaobiet** [GiraffeLe/openwrt-with-ua2f#1]
我按照教程自己编译了几个包，ua2f雀氏启动了，当我打开登录giwifi网址时显示403，用你的包就没问题，为啥啊

**Comment by GiraffeLe** [comment]
旧版ua2f启动之后ua就变成了ffff,验证页面检测到ua异常,会报403,把ua2f插件先关闭然后再进入验证界面登录,登陆成功之后再重新打开插件即可
