### ISSUE TITLE
适用于所有设备吗

### ISSUE THREAD

**Issue by 2373578489** [GiraffeLe/openwrt-with-ua2f#2]
我的是小米4c路由器，已经刷入了OpenWrt，这个方法还适用吗？需要我重新编译固件吗？我是小白，大佬能给个详细教学吗

**Comment by GiraffeLe** [comment]
> 我的是小米4c路由器，已经刷入了OpenWrt，这个方法还适用吗？需要我重新编译固件吗？我是小白，大佬能给个详细教学吗

能刷openwrt就可以，不过需要你再重新编译一个带ua2f的固件。
